language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy-5.6.0
    - pypy3.3-5.5-alpha
install:
    - pip install -U pip setuptools # need updated pip for caching
    - pip install -U coverage coveralls
    - pip install -U -e .[test]
script:
    - coverage run -m zope.intid.tests
after_success:
    - coveralls
notifications:
    email: false

cache: pip
